#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

//! This file is automatically generated by rust-bindgen and modified for more easy use.
//!
//! From header file `include/hci_socket.bluetooth/hci_socket.bluetooth.h`
pub mod hci;
pub mod l2cap;

/// #define BTPROTO_HCI  1
pub const BTPROTO_HCI: i32 = 1;
/// #define BTPROTO_L2CAP        0
pub const BTPROTO_L2CAP: i32 = 0;